# Generated by Django 4.2 on 2025-05-24 15:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nama model, cth: Student Risk Predictor', max_length=200)),
                ('description', models.TextField(help_text='Deskripsi singkat mengenai kasus penggunaan dan tujuan model.')),
                ('model_type', models.CharField(choices=[('Classification', 'Classification'), ('Regression', 'Regression'), ('Clustering', 'Clustering')], help_text='Jenis model machine learning.', max_length=50)),
                ('creator', models.CharField(help_text='Nama anggota tim yang membuat model.', max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, help_text='Tanggal model dibuat.')),
                ('dataset_name', models.CharField(help_text='Nama dataset yang digunakan untuk training, cth: Student Performance Data 2024', max_length=100)),
                ('file_path', models.CharField(help_text='Path relatif ke file .pkl, cth: ml_models/miko_student_risk_pipeline.pkl', max_length=255)),
                ('explainer_path', models.CharField(blank=True, help_text='Path ke file explainer .pkl (jika ada).', max_length=255, null=True)),
                ('features_path', models.CharField(blank=True, help_text='Path ke file nama fitur .pkl (jika ada).', max_length=255, null=True)),
                ('endpoint_url_name', models.CharField(help_text='Nama URL pattern dari halaman prediksi, cth: usecase_miko:predict_risk', max_length=100)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
