# Generated by Django 4.2 on 2025-05-26 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodel',
            name='scaler_path',
            field=models.CharField(blank=True, help_text='Path ke file scaler .pkl (jika ada, untuk model seperti Isolation Forest).', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='explainer_path',
            field=models.CharField(blank=True, help_text='Path ke file explainer .pkl (jika ada, untuk model seperti SHAP).', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='file_path',
            field=models.CharField(help_text='Path relatif ke file .pkl model utama, cth: ml_models/miko_student_risk_pipeline.pkl', max_length=255),
        ),
    ]
